/**
 * Carapace error codes and error payload types.
 *
 * Error codes are split into two categories:
 *   - Pipeline errors: generated by the core's 6-stage validation pipeline.
 *   - Handler errors: generated by the core on behalf of plugin handlers,
 *     or by the handler itself via ToolError.
 *
 * See docs/ARCHITECTURE.md § Error Response for the full specification.
 */

// ---------------------------------------------------------------------------
// Error codes
// ---------------------------------------------------------------------------

/**
 * All machine-readable error codes in the protocol.
 *
 * Pipeline codes (stages 2-5) are reserved — if a handler throws a ToolError
 * with one of these codes, the core normalises it to HANDLER_ERROR.
 */
export const ErrorCode = {
  // Pipeline errors (generated by core)
  UNKNOWN_TOOL: 'UNKNOWN_TOOL',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMITED: 'RATE_LIMITED',
  CONFIRMATION_TIMEOUT: 'CONFIRMATION_TIMEOUT',
  CONFIRMATION_DENIED: 'CONFIRMATION_DENIED',

  // Handler errors (generated by core on behalf of handler)
  PLUGIN_TIMEOUT: 'PLUGIN_TIMEOUT',
  PLUGIN_UNAVAILABLE: 'PLUGIN_UNAVAILABLE',
  PLUGIN_ERROR: 'PLUGIN_ERROR',

  // Handler errors (generated by plugin handler via ToolError)
  HANDLER_ERROR: 'HANDLER_ERROR',
} as const;

/** Union of all error code string values. */
export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

// ---------------------------------------------------------------------------
// Error payload
// ---------------------------------------------------------------------------

/**
 * Structured error object carried inside a ResponsePayload.
 *
 * Required fields are always present. Optional fields appear only when
 * applicable (e.g. `stage` for pipeline errors, `retry_after` for rate
 * limits).
 */
export interface ErrorPayload {
  /** Machine-readable error code. */
  code: ErrorCodeValue;
  /** Human-readable explanation for Claude. */
  message: string;
  /** Whether the same request might succeed if retried. */
  retriable: boolean;
  /** Pipeline stage (1-6) that rejected the request. */
  stage?: number;
  /** Which argument field failed validation. */
  field?: string;
  /** Seconds to wait before retrying (for rate limits). */
  retry_after?: number;
}

// ---------------------------------------------------------------------------
// Retriability defaults
// ---------------------------------------------------------------------------

/**
 * Default `retriable` value for each error code.
 *
 * Handlers may override this for HANDLER_ERROR; the core uses these
 * defaults for all pipeline-generated and core-generated errors.
 */
export const ERROR_RETRIABLE_DEFAULTS: Record<ErrorCodeValue, boolean> = {
  [ErrorCode.UNKNOWN_TOOL]: false,
  [ErrorCode.VALIDATION_FAILED]: false,
  [ErrorCode.UNAUTHORIZED]: false,
  [ErrorCode.RATE_LIMITED]: true,
  [ErrorCode.CONFIRMATION_TIMEOUT]: true,
  [ErrorCode.CONFIRMATION_DENIED]: false,
  [ErrorCode.PLUGIN_TIMEOUT]: true,
  [ErrorCode.PLUGIN_UNAVAILABLE]: true,
  [ErrorCode.PLUGIN_ERROR]: false,
  [ErrorCode.HANDLER_ERROR]: false,
};

// ---------------------------------------------------------------------------
// Reserved pipeline codes
// ---------------------------------------------------------------------------

/**
 * The 6 pipeline error codes that are reserved for core use.
 *
 * If a handler throws a ToolError with any of these codes, the core
 * normalises it to HANDLER_ERROR and preserves the original message.
 */
export const RESERVED_PIPELINE_CODES: ReadonlySet<ErrorCodeValue> = new Set([
  ErrorCode.UNKNOWN_TOOL,
  ErrorCode.VALIDATION_FAILED,
  ErrorCode.UNAUTHORIZED,
  ErrorCode.RATE_LIMITED,
  ErrorCode.CONFIRMATION_TIMEOUT,
  ErrorCode.CONFIRMATION_DENIED,
]);
