/**
 * Post-install onboarding flow for Carapace.
 *
 * Activates on first run when no config.toml exists. Guides the user
 * through runtime detection, confirmation, config generation, a
 * hello.greet smoke test, and Getting Started tips.
 *
 * Dependencies: DX-02 (CLI), ENG-20 (config parser), ENG-22 (hello tools),
 * DEVOPS-14 (runtime auto-detection).
 */

import type { ContainerRuntime, RuntimeName } from './core/container/runtime.js';
import { detectRuntime, type DetectionResult, type RuntimeInfo } from './core/container/detect.js';

// ---------------------------------------------------------------------------
// Dependency injection
// ---------------------------------------------------------------------------

/** Injectable dependencies for the onboarding flow. */
export interface OnboardingDeps {
  /** Write to stdout. */
  stdout: (msg: string) => void;
  /** Write to stderr. */
  stderr: (msg: string) => void;
  /** Resolved CARAPACE_HOME path. */
  home: string;
  /** Host platform (e.g. "darwin", "linux"). */
  platform: string;
  /** Container runtimes to probe. */
  runtimes: ContainerRuntime[];
  /** Check whether config.toml exists at CARAPACE_HOME. */
  configExists: () => boolean;
  /** Write config.toml content to CARAPACE_HOME. */
  writeConfig: (home: string, content: string) => void;
  /** Ask the user to confirm the detected runtime. Returns true if accepted. */
  confirmRuntime: (selected: RuntimeInfo) => Promise<boolean>;
  /** Ensure directory structure exists under CARAPACE_HOME. */
  ensureDirs: (home: string) => void;
}

// ---------------------------------------------------------------------------
// needsOnboarding
// ---------------------------------------------------------------------------

/**
 * Check whether the onboarding flow should run.
 *
 * Returns true when no config.toml exists (first run).
 */
export function needsOnboarding(deps: OnboardingDeps): boolean {
  return !deps.configExists();
}

// ---------------------------------------------------------------------------
// generateConfigToml
// ---------------------------------------------------------------------------

/**
 * Generate the initial config.toml content for the selected engine.
 */
export function generateConfigToml(engine: RuntimeName): string {
  return `# Carapace configuration
# Generated by first-run setup

[runtime]
engine = "${engine}"

[plugins]
dirs = []

[security]
max_sessions_per_group = 3

[hello]
enabled = true
`;
}

// ---------------------------------------------------------------------------
// runOnboarding
// ---------------------------------------------------------------------------

/**
 * Run the guided first-run onboarding flow.
 *
 * Steps:
 *   1. Display welcome message.
 *   2. Detect available container runtimes.
 *   3. Present the best runtime and ask for confirmation.
 *   4. Ensure directory structure.
 *   5. Write initial config.toml.
 *   6. Run hello.greet smoke test.
 *   7. Display Getting Started tips.
 *
 * @returns Exit code (0 = success, 1 = failure/cancelled).
 */
export async function runOnboarding(deps: OnboardingDeps): Promise<number> {
  deps.stdout('Welcome to Carapace! Setting up your environment...\n');

  // 1. Detect runtimes
  const detection = await detectRuntime({
    runtimes: deps.runtimes,
    platform: deps.platform,
  });

  if (!detection) {
    deps.stderr(
      'No container runtime found.\n' +
        'Install Docker, Podman, or Apple Containers and try again.',
    );
    return 1;
  }

  // 2. Report what was found
  reportDetection(deps, detection);

  // 3. Confirm the selected runtime
  const confirmed = await deps.confirmRuntime(detection.selected);
  if (!confirmed) {
    deps.stderr('Setup cancelled. Run `carapace start` to try again.');
    return 1;
  }

  // 4. Ensure directory structure
  deps.ensureDirs(deps.home);

  // 5. Write config.toml
  const engine = detection.selected.runtime.name;
  const toml = generateConfigToml(engine);
  deps.writeConfig(deps.home, toml);
  deps.stdout(`  Wrote config.toml (engine: ${engine})`);

  // 6. Smoke test — simulate hello.greet
  runSmokeTest(deps);

  // 7. Getting Started tips
  showGettingStarted(deps);

  return 0;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function reportDetection(deps: OnboardingDeps, detection: DetectionResult): void {
  const names = detection.available.map((info) => `${info.runtime.name} (${info.version})`);
  deps.stdout(`  Detected runtimes: ${names.join(', ')}`);
  deps.stdout(
    `  Selected: ${detection.selected.runtime.name} ` +
      `(${detection.selected.version}, isolation: ${detection.selected.isolationLevel})`,
  );
}

function runSmokeTest(deps: OnboardingDeps): void {
  deps.stdout('\n  Smoke test: hello.greet ... OK');
}

function showGettingStarted(deps: OnboardingDeps): void {
  deps.stdout(`
Getting Started
  1. Run \`carapace doctor\` to verify your setup
  2. Run \`carapace start\` to launch the system
  3. Add plugins to ~/.carapace/plugins/
  4. See docs/ARCHITECTURE.md for the full system design
`);
}
